# Generated by Django 5.2.8 on 2025-11-26 10:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dd2gf8ina/image/upload/v1764151418/avatar_qp6fuj.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
