# Generated by Django 5.2.8 on 2025-11-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='xp_required',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
