# Generated by Django 5.2.8 on 2025-11-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_badge_xp_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='days_required',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
